name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Shellcheck
      uses: ludeeus/action-shellcheck@v1
      with:
        args: scripts/*.sh
